title: Bioinformatician | Shripad Sinari
description:  Resume
url: https://ssinari.github.io/bioinfo
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
